force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER - {0000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>Additional Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Logged_In_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_User__c</fullName>
    <label>Logged In User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_Reference__c.field-meta.xml
<CustomField>
    <fullName>Record_Reference__c</fullName>
    <label>Record Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogger.cls
public without sharing class ErrorLogger {
    
    public static String LogError(String ComponentName, String ComponentType,
                                          String ErrorMessage, String ErrorDescription, String ErrorCode,
                                          String RecordReference, String AdditionalInfo)
    {
        Error_Log__c er = new Error_Log__c();
        
        er.Component_Name__c=ComponentName;
        er.Component_Type__c=ComponentType;
        
        er.ErrorMessage__c=ErrorMessage;
        er.Error_Description__c=ErrorDescription;
        er.Error_Code__c=ErrorCode;
        
        er.Record_Reference__c = RecordReference;
        er.Additional_Info__c=AdditionalInfo;
        
        er.Logged_In_User__c=UserInfo.getUserId();
        insert er;
        return er.Name; 
    }

}