force-app/main/default/objects/Filter__c/Filter__c.object-meta.xml
<CustomObject>
    <label>Filter</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Filter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter__c/fields/displayText__c.field-meta.xml
<CustomField>
    <fullName>displayText__c</fullName>
    <label>displayText</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>fieldAPIName__c</fullName>
    <label>fieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldLabel__c.field-meta.xml
<CustomField>
    <fullName>fieldLabel__c</fullName>
    <label>fieldLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldType__c.field-meta.xml
<CustomField>
    <fullName>fieldType__c</fullName>
    <label>fieldType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/filterString__c.field-meta.xml
<CustomField>
    <fullName>filterString__c</fullName>
    <label>filterString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/isrelated__c.field-meta.xml
<CustomField>
    <fullName>isrelated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isrelated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/objectName__c.field-meta.xml
<CustomField>
    <fullName>objectName__c</fullName>
    <formula>View__r.objectName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>objectName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/operatorLabel__c.field-meta.xml
<CustomField>
    <fullName>operatorLabel__c</fullName>
    <label>operatorLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/operatorSymbol__c.field-meta.xml
<CustomField>
    <fullName>operatorSymbol__c</fullName>
    <label>operatorSymbol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/relationshipFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>relationshipFieldAPIName__c</fullName>
    <label>relationshipFieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/relObjName__c.field-meta.xml
<CustomField>
    <fullName>relObjName__c</fullName>
    <label>relObjName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/serial__c.field-meta.xml
<CustomField>
    <fullName>serial__c</fullName>
    <label>serial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/valuetoFilter__c.field-meta.xml
<CustomField>
    <fullName>valuetoFilter__c</fullName>
    <label>valuetoFilter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <label>View</label>
    <referenceTo>View__c</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/View__c/View__c.object-meta.xml
<CustomObject>
    <label>View</label>
    <nameField>
        <label>View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/View__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/View__c/fields/CustomLogic__c.field-meta.xml
<CustomField>
    <fullName>CustomLogic__c</fullName>
    <label>CustomLogic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/View__c/fields/Field_To_Display_JSON__c.field-meta.xml
<CustomField>
    <fullName>Field_To_Display_JSON__c</fullName>
    <label>Fields To Display JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/View__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/View__c/fields/objectName__c.field-meta.xml
<CustomField>
    <fullName>objectName__c</fullName>
    <label>objectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataSearchController.cls
public with sharing class DataSearchController {
    
    //public static String allowedFieldTypes = 'Boolean,Currency,Date,DateTime,Double,Email,ID,Integer,Long,MultiPicklist,Percent,Phone,Picklist,String,TextArea,Time,URL';
    
    public static String allowedObjectTypes=System.Label.AQB_AllowedObjects;
    public static String allowedFieldTypes = System.Label.AQB_AllowedFieldTypes;
    public static String notAllowedObjectType=System.Label.AQB_NA_ObjectTypes;
    @AuraEnabled
    public static List<ObjectWrapper>  getAllObjectList()
    {
        List<ObjectWrapper> owlist = new List<ObjectWrapper>();
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Set<String> objectKeySet = gd.keySet();
        for(String objKey : objectKeySet)
        {
            List<String> allowedObjectTypeSet = allowedObjectTypes.split(',');
            Schema.DescribeSObjectResult objDetail = gd.get(objKey).getDescribe();
            Boolean isValidObject = false;
            for(String allowed:  allowedObjectTypeSet)
            {
                if(objKey==allowed)
                {
                    isValidObject=true;
                }
            }
            if(isValidObject)
            {
                if((objDetail.isAccessible()&&objDetail.isQueryable())&&objDetail.isDeprecatedAndHidden()==false)
                {
                    ObjectWrapper ow = new ObjectWrapper();
                    
                    ow.ObjectLabel=objDetail.getLabel();
                    ow.ObjectAPIName=objKey;
                    
                    List<RelatedWrapper> relatedLists  = new List<RelatedWrapper>();
                    List<Schema.ChildRelationship> childRelationshiplist = objDetail.getChildRelationships();
                    for(Schema.ChildRelationship cr:childRelationshiplist)
                    {
                        if(!cr.isDeprecatedAndHidden()&&cr.getRelationshipName()!=null){
                            
                            RelatedWrapper rw = new RelatedWrapper();
                            rw.RelatedListSObjectName =  cr.getChildSObject().getDescribe().getName();
                            rw.RelationshipFieldAPIName = cr.getField().getDescribe().getName();
                            rw.RelationshipLabel =  cr.getRelationshipName();
                            Boolean isValidRObject = false;
                            for(String allowed:  allowedObjectTypeSet)
                            {
                                if(cr.getChildSObject().getDescribe().getName()==allowed)
                                {
                                    isValidRObject=true;
                                }
                            }
                            if(isValidRObject)
                            {
                                relatedLists.add(rw);
                            }
                        }
                    }
                    List<FieldWrapper> fieldList = new List<FieldWrapper>();
                    
                    Map <String, Schema.SObjectField> fieldMap = objDetail.fields.getMap();
                    for(String fieldKey : fieldMap.keySet())
                    {
                        Schema.DescribeFieldResult fd = fieldMap.get(fieldKey).getDescribe();
                        if(fd.isAccessible()&&fd.isFilterable()&&(fd.isDeprecatedAndHidden()==false) &&(allowedFieldTypes.containsIgnoreCase(fd.getType().name())))
                        {
                            FieldWrapper fw = new FieldWrapper();
                            fw.FieldAPIName =  fd.getName();
                            fw.FieldLabel =  fd.getLabel();
                            fw.FieldType =  fd.getType().name();
                            if(fw.fieldType == 'REFERENCE')
                            {
                                List<Schema.sObjectType> refrencetoList = fd.getReferenceTo();
                                if(refrencetoList.size()==1){
                                fw.ReferencedSObjectName  = (refrencetoList[0].getDescribe().getName()).toLowerCase();
                                }
							}
                            fieldList.add(fw);
                        }
                    }
                    ow.fieldList = fieldList;
                    ow.relatedLists = relatedLists;
                    owlist.add(ow);
                    
                }
            }
        }
        System.debug('MethodOut');
        return owlist;
    }
    
    @AuraEnabled
    public static ViewWrapper  getView(String viewId)
    {
        try{
            List<View__c> viw=[SELECT Id, Name, CustomLogic__c, Condition__c, Limit__c, objectName__c,Field_To_Display_JSON__c ,
                               (SELECT Id, isrelated__c, fieldType__c, fieldAPIName__c, fieldLabel__c, operatorSymbol__c,operatorLabel__c, valuetoFilter__c, 
                                displayText__c, serial__c, filterString__c, relationshipFieldAPIName__c, relObjName__c, View__c, objectName__c FROM Filters__r)FROM View__c 
                               WHERE Id=:viewId LIMIT 1];
            ViewWrapper vw=new ViewWrapper();
            if(!viw.isEmpty()){
                vw.view=viw[0];
                List<Filter__c> fltrs=viw[0].Filters__r;
                vw.filterList=fltrs;
                
                return vw;
            }else{
                return null;
            }
            
        }catch(Exception e){
            return null;
        }
    }
    
    @AuraEnabled
    public static List<View__c>  getViewList()
    {
        Id userId=UserInfo.getUserId();
        List<View__c> vwList=[select Id,Name,OwnerId from View__c where OwnerId=:userId];
        return vwList;
    }
    
    @AuraEnabled
    public static String  saveView(ViewWrapper viewData)
    {
        try{
          	System.debug(JSON.serialize(viewData));
            View__c vw=viewData.view;
            List<Filter__c> filters=viewData.filterList;
            System.debug('DATA:');
            System.debug(viewData); 
            
            System.debug('viewData.filterList len:'+viewData.filterList.size());
            System.debug('filters len:'+filters.size());
            
            upsert vw;
            Set<Id> filterIdSet=new Set<Id>();
            List<Filter__c> upsertList=new List<Filter__c>();
            for(Filter__c flts:filters){
                if(flts.Id==null){
                    flts.view__c=vw.Id;
                   
                }else{
                    filterIdSet.add(flts.Id);
                }
                upsertList.add(flts);
            }
            System.debug('size: '+upsertList.size());
            
            List<Filter__c> checkFilterList=[select id from Filter__c where View__c=:vw.Id and (NOT Id in :filterIdSet)];
            delete checkFilterList;
            
            upsert upsertList;
            
            return 'Success';
        }catch(Exception e){
            return e.getMessage();
        }
    }
    
    public class ViewWrapper{
        
        @AuraEnabled public View__c view   {get;set;} 
        @AuraEnabled public List<Filter__c> filterList {get;set;}
    }
    
    
    public class ObjectWrapper{
        
        @AuraEnabled public String ObjectAPIName   {get;set;}
        @AuraEnabled public String ObjectLabel   {get;set;}
        @AuraEnabled public List<FieldWrapper> fieldList {get;set;}
        @AuraEnabled public List<RelatedWrapper> relatedLists {get;set;}
    }
    public class FieldWrapper{
        @AuraEnabled public String FieldLabel  {get;set;}
        @AuraEnabled public String FieldAPIName  {get;set;}
        @AuraEnabled public String ReferencedSObjectName  {get;set;}
        @AuraEnabled public String FieldType  {get;set;}
    }
    public class RelatedWrapper{
        @AuraEnabled public String RelationshipLabel {get;set;}
        @AuraEnabled public String RelationshipFieldAPIName {get;set;}
        @AuraEnabled public String RelatedListSObjectName {get;set;}
    }
}