force-app/main/default/objects/Filter__c/Filter__c.object-meta.xml
<CustomObject>
    <label>Filter</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Filter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter__c/fields/displayText__c.field-meta.xml
<CustomField>
    <fullName>displayText__c</fullName>
    <label>displayText</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>fieldAPIName__c</fullName>
    <label>fieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldLabel__c.field-meta.xml
<CustomField>
    <fullName>fieldLabel__c</fullName>
    <label>fieldLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/fieldType__c.field-meta.xml
<CustomField>
    <fullName>fieldType__c</fullName>
    <label>fieldType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/filterString__c.field-meta.xml
<CustomField>
    <fullName>filterString__c</fullName>
    <label>filterString</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/isrelated__c.field-meta.xml
<CustomField>
    <fullName>isrelated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isrelated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/objectName__c.field-meta.xml
<CustomField>
    <fullName>objectName__c</fullName>
    <formula>View__r.objectName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>objectName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/operatorLabel__c.field-meta.xml
<CustomField>
    <fullName>operatorLabel__c</fullName>
    <label>operatorLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/operatorSymbol__c.field-meta.xml
<CustomField>
    <fullName>operatorSymbol__c</fullName>
    <label>operatorSymbol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/relationshipFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>relationshipFieldAPIName__c</fullName>
    <label>relationshipFieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/serial__c.field-meta.xml
<CustomField>
    <fullName>serial__c</fullName>
    <label>serial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/valuetoFilter__c.field-meta.xml
<CustomField>
    <fullName>valuetoFilter__c</fullName>
    <label>valuetoFilter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Filter__c/fields/View__c.field-meta.xml
<CustomField>
    <fullName>View__c</fullName>
    <label>View</label>
    <referenceTo>View__c</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/View__c/View__c.object-meta.xml
<CustomObject>
    <label>View</label>
    <nameField>
        <label>View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/View__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/View__c/fields/CustomLogic__c.field-meta.xml
<CustomField>
    <fullName>CustomLogic__c</fullName>
    <label>CustomLogic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/View__c/fields/Field_To_Display_JSON__c.field-meta.xml
<CustomField>
    <fullName>Field_To_Display_JSON__c</fullName>
    <label>Fields To Display JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/View__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/View__c/fields/objectName__c.field-meta.xml
<CustomField>
    <fullName>objectName__c</fullName>
    <label>objectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataSearchController_Test.cls
@isTest
public class DataSearchController_Test {
    
    @isTest
    private static void ManageViewTest()
    {
      /*  String ViewJSON = '{"view":{"attributes":{"type":"View__c"},"Fields_To_Display_JSON__c":"[{\"value\":\"Name\",\"label\":\"Account Name\",\"Type\":\"STRING\"},{\"value\":\"BillingCity\",\"label\":\"Billing City\",\"Type\":\"STRING\"},{\"value\":\"AccountNumber\",\"label\":\"Account Number\",\"Type\":\"STRING\"},{\"value\":\"AnnualRevenue\",\"label\":\"Annual Revenue\",\"Type\":\"CURRENCY\"}]","Condition__c":"AND","CustomLogic__c":"","Limit__c":"10000","objectName__c":"account","Name":"Test View"},"filterList":[{"attributes":{"type":"Filter__c"},"relationshipFieldAPIName__c":"temp","valuetoFilter__c":"s%","operatorLabel__c":"Starts with","filterString__c":"Name like \'s%\'","operatorSymbol__c":"like","isrelated__c":false,"fieldLabel__c":"Account Name","fieldType__c":"STRING","fieldAPIName__c":"Name","displayText__c":"1. Account Name Starts with s%","serial__c":"1"}]}';
        DataSearchController.ViewWrapper vw = (DataSearchController.ViewWrapper) JSON.deserialize(ViewJSON, DataSearchController.ViewWrapper.Class);
        */
        DataSearchController.ViewWrapper vw = new DataSearchController.ViewWrapper();
        View__c vwrec = new View__c();
        vwrec.Name='Test View';        
        vwrec.objectName__c='account';        
        vwrec.Limit__c='100';        
        vwrec.objectName__c='account';        
        vwrec.Field_To_Display_JSON__c='[{\"value\":\"Name\",\"label\":\"Account Name\",\"Type\":\"STRING\"},{\"value\":\"BillingCity\",\"label\":\"Billing City\",\"Type\":\"STRING\"},{\"value\":\"BillingCountry\",\"label\":\"Billing Country\",\"Type\":\"STRING\"},{\"value\":\"ShippingStreet\",\"label\":\"Shipping Street\",\"Type\":\"TEXTAREA\"},{\"value\":\"ShippingLatitude\",\"label\":\"Shipping Latitude\",\"Type\":\"DOUBLE\"},{\"value\":\"Jigsaw\",\"label\":\"Data.com Key\",\"Type\":\"STRING\"},{\"value\":\"LastActivityDate\",\"label\":\"Last Activity\",\"Type\":\"DATE\"}]';
        List<Filter__c> filterList = new List<Filter__c>();
        Filter__c filter = new Filter__c();
        filter.isrelated__c=false;
        filter.fieldType__c='STRING';
        filter.fieldAPIName__c='Name';
        filter.fieldLabel__c='Account Name';
        filter.operatorSymbol__c='like';
        filter.operatorLabel__c='Starts with';
        filter.valuetoFilter__c='s%';
        filter.displayText__c='1. Account Name Starts with s%';
        filter.serial__c='1';
        
        filter.relationshipFieldAPIName__c='temp';
        filter.filterString__c='Name like \'s%\'';
        filterList.add(filter);
        vw.view = vwrec;
        vw.filterList = filterList;
        DataSearchController.saveView(vw);
        DataSearchController.getView(DataSearchController.getViewList()[0].Id);
    }
        @isTest
    private static void DataSearchInitTest()
    {
        DataSearchController.getAllObjectList();
    }
    
    @isTest
    private static void SearchLwcControllerTest(){
        SearchLwcController.fetchDataRecords('', 'account', 'Id,Name', '100');
        SearchLwcController.getPicklistValues('account', 'Industry');
    }
}