force-app/main/default/objects/Movie__c/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>Gujrati</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Movie_Poster__c.field-meta.xml
<CustomField>
    <fullName>Movie_Poster__c</fullName>
    <label>Movie Poster</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster_Source__c.field-meta.xml
<CustomField>
    <fullName>Poster_Source__c</fullName>
    <label>Poster Source</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BMSController.cls
/**
 * @File Name          : BMSController.cls
 * @Description        : 
 * @Author             : RISHAB GOYAL
 * @Group              : 
 * @Last Modified By   : RISHAB GOYAL
 * @Last Modified On   : 9/28/2019, 3:31:04 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    9/22/2019   RISHAB GOYAL     Initial Version
**/
public with sharing class BMSController {
    @AuraEnabled(cacheable=true)
   public static List<Movie__c> getMovieList()
   {
       return [Select id,Name,Audience__c,Description__c,Languages__c,Movie_Poster__c,Poster_Source__c,Rating__c from Movie__c ];
   }
}