force-app/main/default/objects/Test_2__c/Test_2__c.object-meta.xml
<CustomObject>
    <label>Test 2</label>
    <nameField>
        <label>Test 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_2__c/fields/Boolean2__c.field-meta.xml
<CustomField>
    <fullName>Boolean2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boolean2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateCheckboxController.cls
public with sharing class UpdateCheckboxController {
    
    @AuraEnabled public static void updatecheck(String recid)
    {
        Test_2__c rec= [Select id,Boolean2__c from Test_2__c where id =:recid];
        
        System.debug(rec.Boolean2__c);
        if(rec.Boolean2__c==true)
            {
            rec.Boolean2__c=false;
             }
        else
        {
            rec.Boolean2__c=true;
        }
        update rec;
            
	}

}